name: Recovery Build for SaluteTV AT30A6

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'URL манифеста TWRP'
        required: true
        default: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp'
      MANIFEST_BRANCH:
        description: 'Ветка манифеста TWRP'
        required: true
        default: 'twrp-12.1'
      DEVICE_TREE_URL:
        description: 'URL репозитория дерева устройства'
        required: true
        default: 'https://github.com/SKOCHE/SaluteTV_at30a6_TWRP'
      DEVICE_TREE_BRANCH:
        description: 'Ветка дерева устройства'
        required: true
        default: 'main'
      DEVICE_PATH:
        description: 'Путь к устройству в дереве устройства'
        required: true
        default: 'recovery/root/device/Realtek/at30a6'
      COMMON_TREE_URL:
        description: 'URL общего дерева (если есть)'
        required: false
      COMMON_PATH:
        description: 'Путь к общему дереву (если есть)'
        required: false
      DEVICE_NAME:
        description: 'Имя устройства'
        required: true
        default: 'at30a6'
      MAKEFILE_NAME:
        description: 'Имя Makefile'
        required: true
        default: 'recovery_at30a6'
      BUILD_TARGET:
        description: 'Цель сборки'
        required: true
        default: 'recovery'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-22.04  # Используем Ubuntu 22.04
    permissions:
      contents: write

    steps:
    - name: Display Run Parameters
      run: |
        echo "::group::User Environment Variables"
        echo "Manifest URL: ${{ github.event.inputs.MANIFEST_URL }}"
        echo "Manifest Branch: ${{ github.event.inputs.MANIFEST_BRANCH }}"
        echo "Device Tree URL: ${{ github.event.inputs.DEVICE_TREE_URL }}"
        echo "Device Tree Branch: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}"
        echo "Device Path: ${{ github.event.inputs.DEVICE_PATH }}"
        echo "Device Name: ${{ github.event.inputs.DEVICE_NAME }}"
        echo "Makefile Name: ${{ github.event.inputs.MAKEFILE_NAME }}"
        echo "Build Target: ${{ github.event.inputs.BUILD_TARGET }}.img"
        echo "::endgroup::"

    - name: Check Out
      uses: actions/checkout@v3

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install git gperf build-essential gcc-multilib ccache chrpath gawk flex bison python3 python3-pil \
          libncurses5-dev x11proto-core-dev libx11-dev libreadline6-dev libgl1-mesa-dev \
          tofrodos python3-venv zip lzop pngcrush imagemagick bzip2 libbz2-dev rsync bc \
          openjdk-8-jdk  # Устанавливаем OpenJDK 8

    - name: Установка OpenJDK 8
      run: |
        sudo apt-get install openjdk-8-jdk -y
        sudo update-alternatives --config java
        java -version

    - name: Install repo
      run: |
        mkdir -p ~/bin
        curl -o ~/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize repo
      run: |
        mkdir workspace
        cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        repo init --depth=1 -u ${{ github.event.inputs.MANIFEST_URL }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
      id: pwd

    - name: Repo Sync
      run: |
        repo sync -j$(nproc --all) --force-sync
      working-directory: workspace

    - name: Clone device tree
      run: |
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Clone common tree
      if: |
        github.event.inputs.COMMON_TREE_URL != null
        && github.event.inputs.COMMON_PATH != null
      run: |
        git clone ${{ github.event.inputs.COMMON_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.COMMON_PATH }}
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Sync Device Dependencies (если необходимо)
      run: |
        if [ -f "${GITHUB_WORKSPACE}/scripts/convert.sh" ]; then
          bash ${GITHUB_WORKSPACE}/scripts/convert.sh ${{ github.event.inputs.DEVICE_PATH }}/twrp.dependencies
          repo sync -j$(nproc --all)
        else
          echo "convert.sh script not found. Skipping dependency sync."
        fi
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}
      continue-on-error: true

    - name: Set Swap Space (Опционально)
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Building recovery
      run: |
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch ${{ github.event.inputs.MAKEFILE_NAME }}-eng
        make clean
        make ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc --all)
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ github.event.inputs.BUILD_TARGET }}.img
        name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Manifest: ${{ github.event.inputs.MANIFEST_BRANCH }}
          Device: ${{ github.event.inputs.DEVICE_NAME }}
          Target: ${{ github.event.inputs.BUILD_TARGET }}.img
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
