name: Recovery Build

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'MANIFEST_URL'
        required: true
        default: 'https://github.com/azrim/android_bootable_recovery_manifest'
      MANIFEST_BRANCH:
        description: 'MANIFEST_BRANCH'
        required: true
        default: 'twrp-12.1'
      DEVICE_TREE_URL:
        description: 'DEVICE_TREE_URL'
        required: true
        default: 'https://github.com/SKOCHE/SaluteTV_at30a6_TWRP'
      DEVICE_TREE_BRANCH:
        description: 'DEVICE_TREE_BRANCH'
        required: true
        default: 'main'
      DEVICE_PATH:
        description: 'DEVICE_PATH'
        required: true
        default: 'device/salute/at30a6'
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: true
        default: 'at30a6'
      MAKEFILE_NAME:
        description: 'MAKEFILE_NAME'
        required: true
        default: 'twrp_at30a6'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python3 bc ccache liblz4-tool libsdl1.2-dev lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static
    - name: Set up Java 8
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'
    - name: Install repo
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH
    - name: Init repo
      run: |
        mkdir workspace && cd workspace
        repo init -u ${{ github.event.inputs.MANIFEST_URL }} -b ${{ github.event.inputs.MANIFEST_BRANCH }} --depth=1
    - name: Repo sync
      run: |
        cd workspace
        repo sync -j$(nproc --all) --force-sync
    - name: Clone device tree
      run: |
        cd workspace
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ${{ github.event.inputs.DEVICE_PATH }}
    - name: Build recovery
      run: |
        cd workspace
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch ${{ github.event.inputs.MAKEFILE_NAME }}-eng
        make recoveryimage -j$(nproc --all)
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: recovery-${{ github.event.inputs.DEVICE_NAME }}
        path: workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery.img
